### ISSUE TITLE
Milestone Casa Hacker

### ISSUE THREAD

**Issue by uira** [redelivre/login-cidadao#276]
## [Login Cidadão 2.0](https://github.com/Mutirao/Casa-Hacker/milestone/2)
_Past due by over 1 year - 0% complete_

- [ ] [Suporte ao E-Residency Estonian ID](https://github.com/Mutirao/Casa-Hacker/issues/19)
- [ ] [Plugin OIDC para WordPress](https://github.com/Mutirao/Casa-Hacker/issues/14)
- [ ] [Integração do VotoLegal com LC](https://github.com/Mutirao/Casa-Hacker/issues/13)
- [ ] [Integração com Carteira BlockChain](https://github.com/Mutirao/Casa-Hacker/issues/12)
- [ ] [Gestor de Senhas e Cadastros do Login Cidadão **Plugin p/ Chrome**](https://github.com/Mutirao/Casa-Hacker/issues/11)
